### PR TITLE
fix: update from the old way to manage route

### PR DESCRIPTION
**Pull request by shiipou**
## About this PR

In this PR I've replaced the rootView with lenraRoutes key in the manifest. This allow to easily use the routes in lenra apps. And easily use json routes as well if needed.

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Nesqwik** [comment]
IMO We should update to JSON Routes, not Lenra Routes

**Comment by Nesqwik** [comment]
Is this working ? The routes should be an array, not an object

**Comment by shiipou** [comment]
Fixed @Nesqwik

**Comment by shiipou** [comment]
> IMO We should update to JSON Routes, not Lenra Routes

Yes we need to as seeing what we talk this morning. (Removing lenraroutes from docs and making people use jsonroutes)

**Pull request closed without merging**
